### ISSUE TITLE
ArrowHead

### ISSUE THREAD

**Issue by jlxdp** [h-ikeda/aframe-arrow-component#1]
Is there a plan to add a flag that would change the arrowhead into a circular base instead of a polygon one?

**Comment by h-ikeda** [comment]
@jlxdp 
No, this is just a binding to the three.js ArrowHelper class and it uses the CylinderGeometry with the fixed radialSegments of 5.

https://github.com/mrdoob/three.js/blob/9ef27d1af7809fa4d9943f8d4c4644e365ab6d2d/src/helpers/ArrowHelper.js#L35

If you would like to render smoother one, you need to use the geometries, meshes and lines separately.

**Comment by jlxdp** [comment]
I see. Thank you for clarifying on this!

Will close this issue now 👍
